apiVersion: v1
kind: Service
metadata:
  name: {{ include "exposeOidc.fullname" . }}
  labels: {{ include "exposeOidc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.exposeOidc.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.exposeOidc.service.port }}
      targetPort: {{ .Values.exposeOidc.port | default "http" }}
      protocol: TCP
      name: http
  selector:
    {{- include "exposeOidc.selectorLabels" . | nindent 4 }}
